/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMeComponent: typeof import('./src/components/aboutMeComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/headerComponent.vue')['default']
    PhotoComponent: typeof import('./src/components/PhotoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkComponent: typeof import('./src/components/workComponent.vue')['default']
  }
}
